[package]
name = "application"
version = "0.0.0"
workspace = "../../"
publish = false

[dependencies]
rocket = { path = "../../core/lib" }
rocket_contrib = { path = "../../contrib/lib" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
formdata = "0.12.2"
image = "0.20.1"